workflows:
  build_melfitness:
    name: Build melfitness_flutter
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Build iOS (real device - no code signing)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - britessantanamilena@gmail.com
