workflows:
  build-ios-without-signing:
    name: Build iOS IPA Only
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
       flutter: stable
    scripts:
      - name: Flutter clean
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build IPA without signing
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - britessantanamilena@gmail.com
